development:
  sessions:
    default:
      database: bootstrap_data_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0

test:
  sessions:
    default:
      database: bootstrap_data_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      database: bootstrap_data_production
      hosts:
        - linus.mongohq.com:10034
      username: ENV["MONGO_USER"]
      password: ENV["MONGO_PASS"]
